### ISSUE TITLE
Remove tooltip?

### ISSUE THREAD

**Issue by ajbraus** [TerryMooreII/angular-wysiwyg#10]

**Comment by mimiflynn** [comment]
I'm getting an error on line 90 regarding `.tooltip` as well. Missing dependency?

**Comment by TerryMooreII** [comment]
jquery is required because of bootstrap but not is part of the dependency list.  I am in the process of updating that.

**Comment by TerryMooreII** [comment]
Jquery is added as a bower dependancy
