### ISSUE TITLE
Quote button doesn't unquote text

### ISSUE THREAD

**Issue by ajbraus** [TerryMooreII/angular-wysiwyg#12]
You literally get stuck in quote.

Maybe I take it back about this library! Might need some more testing.

**Comment by AntonBukov** [comment]
We have the same problem with wysiwyg in our site. How can we solve it?

**Comment by TerryMooreII** [comment]
@AntonBukov Yes this is known issue, its been a while since I have looked into it but if I remember correctly its an issue with the underlining javascript implementation of document.executeCommand.  I will keep looking into so I can get it fixed for hte next release.
