### ISSUE TITLE
multiple instance support is broken in the new version

### ISSUE THREAD

**Issue by flc** [TerryMooreII/angular-wysiwyg#19]
it was fixed already in this pull request https://github.com/TerryMooreII/angular-wysiwyg/pull/18
but you seemed to revert the change with this commit: https://github.com/TerryMooreII/angular-wysiwyg/commit/987690f260b480b62fc9f4a9a6b4b3a2c09236b8
is there a reason why?

**Comment by flc** [comment]
ah, ok so that pr wasnt merged in the first place ... hopefully soon

**Comment by TerryMooreII** [comment]
Whoa, thanks for pointing this out.  I am not sure what happened.  I will get that fixed asap.
