### ISSUE TITLE
tooltip issue

### ISSUE THREAD

**Issue by enkodellc** [TerryMooreII/angular-wysiwyg#2]
I am using meanio https://github.com/linnovate/mean and the dynamic twitter bootstrap tooltip is erroring out. I can manually do tooltips.

Any insight on why. I am using ui-bootstrap as well as bootstrap.

```
element.find('button[title]').tooltip({container: 'body'})
```

**Comment by pcbulai** [comment]
Any update on this? I can encounter this as well.

**Comment by pcbulai** [comment]
Seems to me that by removing `enable-bootstrap-title="true"` I managed to solve the issue.

**Comment by enkodellc** [comment]
I switched to https://github.com/fraywing/textAngular and then recently to Froala -> https://github.com/froala/angular-froala and Froala seems to have every option I have been searching for.
