### ISSUE TITLE
Add jquery to the dependency list?

### ISSUE THREAD

**Issue by Reklino** [TerryMooreII/angular-wysiwyg#24]
Jquery isn't listed as a dependency, but it doesn't seem to function properly without it. So to save confusion it may be best to add jquery as a dependency in the bower.json and in the readme :). Great little module!

**Comment by TerryMooreII** [comment]
I am in the process of fixing some issues and upgrading the some features so I will add this to the list.  I will also test this with out having jquery installed to make sure that it works with out it.  

Thanks

**Comment by TerryMooreII** [comment]
Added to the list and will be in the next release.  Thanks
