### ISSUE TITLE
Add headers

### ISSUE THREAD

**Issue by mgohin** [TerryMooreII/angular-wysiwyg#27]
Can you add headers ? h1, h2, h3 ...

**Comment by Reklino** [comment]
+1

**Comment by TerryMooreII** [comment]
Added heading drop down for H1-H6.  Please test this for me and let me know if you have any issues before I update bower. Thanks

**Comment by mgohin** [comment]
Thanks for you reactivity.
It's almost working, just an error when clicking the select box then clicking outside it (so I'm not selecting any option)

    Error: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at Error (native)
    at itemIs (http://0.0.0.0:9002/bower_components/angular-wysiwyg/angular-wysiwyg.js:263:49)
    at http://0.0.0.0:9002/bower_components/angular-wysiwyg/angular-wysiwyg.js:222:37
    at http://0.0.0.0:9002/bower_components/angular/angular.js:16205:28
    at completeOutstandingRequest (http://0.0.0.0:9002/bower_components/angular/angular.js:4902:10)
    at http://0.0.0.0:9002/bower_components/angular/angular.js:5282:7

**Comment by TerryMooreII** [comment]
Well, that's not good.  I will take a look at that issue with I get home this evening.  

Thanks for testing.

**Comment by Reklino** [comment]
Now that there are headers (which is nice) it would also be nice if there was a 'default' option for the 'font-size' dropdown. Otherwise, once you define a header's font size, you are never able to revert to what it's default size was.

**Comment by mgohin** [comment]
Good idea, maybe a different ticket not to mix asked features ?

**Comment by TerryMooreII** [comment]
@Reklino So are you saying that when you select a Heading size then the font size drop down should switch to a default 'Select Font Size' message?

**Comment by TerryMooreII** [comment]
@Reklino Also I was not able to reproduce that message that you received.

**Comment by Reklino** [comment]
Not exactly. What I'm suggesting is that there is always a 'default' or 'auto' option in the font size drop down. If you change the font size of a header, there is no way to get back to the default font size of the header. I hope that makes sense :). I can open a separate issue as mgohin suggested if you want.

The error message was from @mgohin. I have not encountered the error message yet either.

**Comment by mgohin** [comment]
If I'm the only one getting this error it's probably because of something else (another lib maybe). Could you release so I can use it with bower please ?

**Comment by mgohin** [comment]
@TerryMooreII What @Reklino would like is to remove the attribute on a text, for example I select 16px for a text I get :

    <span style="font-weight: bold;font-size: x-large;">test text</span>

With an option 'default' it removes the font-size attribute, In my case simply :

    <span style="font-weight: bold;">test text</span>

**Comment by mgohin** [comment]
Hi,

I see you have released 1.2, it worked this morning but not anymore

    bower angular-wysiwyg#~1.2  not-cached git://github.com/TerryMooreII/angular-wysiwyg.git#~1.2
    bower angular-wysiwyg#~1.2     resolve git://github.com/TerryMooreII/angular-wysiwyg.git#~1.2
    bower angular-wysiwyg#~1.2     ENORESTARGET No tag found that was able to satisfy ~1.2

**Comment by TerryMooreII** [comment]
Well crap, I will fix that when I get home, sorry about that.

**Comment by TerryMooreII** [comment]
Bower version is fixed.  Thanks for letting me know.

**Comment by mgohin** [comment]
Works like a charm, thx
