### ISSUE TITLE
Problem when using 2 times in the same page

### ISSUE THREAD

**Issue by mgohin** [TerryMooreII/angular-wysiwyg#28]
My html

    <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
            <label class="control-label">My label 1</label>
            <wysiwyg ...></wysiwyg>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
            <label class="control-label">My label 2</label>
            <wysiwyg ...></wysiwyg>
          </div>
        </div>
      </div>

Here is the result
![capture d ecran 2015-04-01 a 09 45 19](https://cloud.githubusercontent.com/assets/3430304/6936565/da3cebb8-d853-11e4-9859-7abef2eb5bb8.png)

I guess the problem comes from selections like ```var menuDiv = document.querySelector('div.wysiwyg-menu');``` because your are not selecting from the ```element``` var given in the link function.

Any chances to get a quick fix ?

**Comment by TerryMooreII** [comment]
Fixed in v 1.2.2

**Comment by mgohin** [comment]
Thanks, works well
