### ISSUE TITLE
Add a selectbox to apply custom css classes

### ISSUE THREAD

**Issue by mgohin** [TerryMooreII/angular-wysiwyg#29]
Hi,

to avoid any complicated custom buttons, could we have a selectbox where we can supply some css classes to apply on a selected text ?

Would be an awesome feat to provide custom css easily.

**Comment by Reklino** [comment]
That would be a cool feature. +1

**Comment by TerryMooreII** [comment]
Interesting.  Let me think that over and see what I can do.

**Comment by mgohin** [comment]
Sorry to bother, but any chances to get something soon ? I'm using your project and we need this kind of feature soon :D

Thx

**Comment by mgohin** [comment]
Up, sorry but the need is getting urgent for us and I would like to keep a nice updated angular-wysiwyg instead of a custom fork

**Comment by TerryMooreII** [comment]
Sorry that this has been taking awhile, I have been very busy lately.  If you have this implemented then I will be happy to take a pull request.

**Comment by mgohin** [comment]
no I don't, I've only made a PR for the link title, and I will not have the time to do it too :(
I get it you are busy, I'm too ^^

**Comment by mgohin** [comment]
Ok i'm on it, it's working, I'll PR in few minutes

**Comment by mgohin** [comment]
done here #33 please take a look at #31 too ;)
