### ISSUE TITLE
Manage link

### ISSUE THREAD

**Issue by mgohin** [TerryMooreII/angular-wysiwyg#30]
Hi,

I need to use links to show a title instead of link. Today it's

```
<a href="http://www.google.fr">http://www.google.fr</a>
```

I would like to be able to do

```
<a href="http://www.google.fr">access google page</a>
```

To do so a simple way would be to add another alertbox to enter en title

**Comment by mgohin** [comment]
I added a very simple PR #31

**Comment by TerryMooreII** [comment]
Sorry for the late response.  I will look this over and get it add asap. 

thanks
