### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by mgohin** [TerryMooreII/angular-wysiwyg#34]
Hi,

can you use angular array annotation like

    someModule.controller('MyController', ['$scope', 'greeter', function($scope, greeter) {
      // ...
    }]);

and use like jshint (easy with grunt task) to correct missing semicolon, double quotes etc ?

I just spent 30min to fix the script in a fork (I can't PR because there is code you don't want).

Thanks

**Comment by TerryMooreII** [comment]
The gulp task now lints and runs ng-min to minify code with the bracket notation
