### ISSUE TITLE
textareaPlaceholder does not work

### ISSUE THREAD

**Issue by michal-husak** [TerryMooreII/angular-wysiwyg#36]
In your code I found
```javascript
...
textareaPlaceholder: '@textareaPlaceholder',
...
```
so I tried
```html
<wysiwyg
        textarea-id="question"
        textarea-class="form-control"
        textarea-height="250px"
        textarea-name="textareaQuestion"
        textarea-required
        ng-model="reportItem.notes.text"
        enable-bootstrap-title="true"
        ng-if="editMode"
        textarea-menu="wysiwygMenu"
        textarea-placeholder="Add some notes to the chart.">
```
and it doesn't show the placeholder text in the wysiwyg "text area". Am I doing something wrong or this is just not functional?
Thx

**Comment by TerryMooreII** [comment]
@michal-husak Im sorry but that is not longer supported.  It was left over from when I was using an actual textarea html control and not the contenteditable div.  Unfortunately contenteditable divs dont have a placeholder attribute.  

I need to update the docs to reflect this.  Sorry for the confusion

**Comment by LTroya** [comment]
Is there a solution using the resource of directive to add a placeholder?

**Comment by michal-husak** [comment]
Hi,

I cannot find any. You have to code it :)

Michal

**Comment by Awea** [comment]
You can simply re-bind the `textarea-placeholder` then add a bit of css to use the placeholder in your contenteditable div :

```
[contenteditable=true]:empty:before {
  content: attr(placeholder);
  display: block; /* For Firefox */
}
```

Thanks to http://codepen.io/flesler/pen/AEIFc :)

**Comment by jualoppaz** [comment]
@Awea your css solution is wonderful, but you need first to extend the directive with the placeholder atribute mapping in the config method of your main module definition:

```
$provide.decorator('wysiwygDirective', function($delegate) {
        var directive = $delegate[0];
        angular.extend(directive.scope, {
            textareaPlaceholder:'@'
        });
        return $delegate;
});
```

It is needed because the "placeholder" attribute is printed in the directive html but it has been removed in the directive scope definition :+1:
