### ISSUE TITLE
When writing the cursor starts at position  initial

### ISSUE THREAD

**Issue by Rossalia** [TerryMooreII/angular-wysiwyg#37]
When I'm writing and the clicked on any option (e.g. bold, font-size..) and I keep writing the cursor begins at the starting position of textarea. How can I fix this?

I would appreciate any help :) :+1:

**Comment by TerryMooreII** [comment]
I am unable to reproduce this issue.  Can you provide more information?

**Comment by Rossalia** [comment]
I'm sorry  I realized it was my error. I had conflict with another direcitve causing the issue.
Thank you so much for your atention.
