### ISSUE TITLE
Submission on button click?

### ISSUE THREAD

**Issue by mdridley** [TerryMooreII/angular-wysiwyg#38]
My form keeps trying to submit every time I click one of the buttons. Not seeing anything special in my form that would cause this. Has anyone else seen this?

**Comment by mackram** [comment]
yes i agree to this by default a button is a submit buttons as can be seen by the below excerpt from MDN.
>submit: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.

I have done a very simple solution myself by adding the following
	  if( obj.tag == 'button' ){
		el.setAttribute('type', 'button');
          }
at line 379

**Comment by TerryMooreII** [comment]
I will update all buttons to to have a type of button so that this doenst happen

**Comment by mdridley** [comment]
Awesome, thanks for the amazing response. Will update ASAP.
