### ISSUE TITLE
'HTML Source' button

### ISSUE THREAD

**Issue by micbsv** [TerryMooreII/angular-wysiwyg#41]
Are there any plans to add this button?
Thank you for the nice control!

**Comment by TerryMooreII** [comment]
Are you just looking for a button to show the html that this wysiwyg is generating?

**Comment by micbsv** [comment]
I need the functionality that the '<> Source' button provides on the CKEditor: http://ckeditor.com/demo

**Comment by shammy** [comment]
I used xeditable plugin to duplicate '<> Source'
<div><h6>Edit HTML: <span class="fa fa-pencil" ng-click="htmlDataForm.$show()" ng-hide="htmlDataForm.$visible"></span></h6>
<p style="height:auto; width:100%; border: 1px solid #ddd" ng-model="data.text" editable-textarea="data.text" e-form="htmlDataForm" e-rows="5" e-cols="25">{{data.text}}</p>
</div>

**Comment by TerryMooreII** [comment]
You should be able to do this out side of the wysiwyg editor by displaying the content of the bound scope variable in a div or text area.  However I will add this as a future feature.
