### ISSUE TITLE
angular-wysiwyg doesn't work well with IE 9

### ISSUE THREAD

**Issue by sylhero** [TerryMooreII/angular-wysiwyg#46]
in IE 9 the icons are surrounded by undefined. Any idea?

**Comment by camillewall** [comment]
I had the same problem in IE11.  I was able to fix it by changing some of the javascript code.  I am going to attempt to get the changes made in the library.

**Comment by rabbit-fdeus** [comment]
I also have the same problem, with Safari 7.1.
Any idea how to fix it?

**Comment by TerryMooreII** [comment]
Just merged in pull request Fix #47.  Please pull down the latest and verify that if fixes this issue

**Comment by nilpaco** [comment]
Still not working here.

![Uploading asdfasdf.PNG…]()
