### ISSUE TITLE
Setting Height not working

### ISSUE THREAD

**Issue by lexingtonclayw1** [TerryMooreII/angular-wysiwyg#9]
I have worked with the Plunker code and also downloaded the copy but I am unable to change the height of the actual WYSIWYG box.  It is staying at the default height.  Any thoughts?

**Comment by Mord-Syth** [comment]
You may use 'ng-attr-style' instead of 'style' for textArea. It seems that IE understands it.

**Comment by TerryMooreII** [comment]
@Mord-Syth thanks that fixed the issue.
